import Link from 'next/link';
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-white shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16">
              <div className="flex">
                <Link href="/" className="flex items-center">
                  Crowd Connect RSVP
                </Link>
              </div>
              <div className="flex items-center space-x-4">
                <Link href="/admin" className="text-gray-700 hover:text-blue-600">Admin</Link>
                <Link href="/agent" className="text-gray-700 hover:text-blue-600">Agent</Link>
                <Link href="/attendee" className="text-gray-700 hover:text-blue-600">Attendee</Link>
              </div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
